### ISSUE TITLE
Toggle to choose the icon pack during installation

### ISSUE THREAD

**Issue by rottenorangee** [ArmashOnGit/lawnchair12l#1]
Hey there! Love the launcher so far... it's been an absolute blast!

Could you consider adding a toggle for icon pack selection during the module installation? It would greatly enhance user customization. (i.e, the official Lawnicons by the Lawnchair team rather than the one by Teamfiles, https://github.com/LawnchairLauncher/lawnicons)

**Comment by ArmashOnGit** [comment]
Sure... I'll release an update which should address this by the following week. Alternatively, u could also replace the Teamfile's Lawnicons with the official one by extracting the module
